Sprites
Atsocs/cobrITA pull request #5
Opened 2021-04-07 16:05 UTC by gbrlbrbs

adicionada uma classe para ler spritesheets e retornar sprites, além de refatoração dos sprites de Snake e Food

2021-04-08 20:28 UTC, Atsocs commented on resources/sprites/Character.json
> +}
deixa uma linha em branco no final do arquivo por favor

2021-04-08 20:30 UTC, Atsocs commented on definitions.py
> +
pode apagar coisas que não são mais usadas sem medo, o git avisa que foi deletado

2021-04-08 20:31 UTC, Atsocs commented on definitions.py
> +SNAKE_SPRITESHEET = 'Character'
esse tipo de constante não sei se faz mt sentido... seria melhor utilizar a string diretamente no codigo, afinal ela só é utilizada uma vez e n depende da estrutura de pastas

2021-04-08 21:02 UTC, Atsocs requested changes
Precisamos de scripts de conversão json/txt/tmx!

2021-04-08 21:02 UTC, Atsocs commented on components/Food.py
> +        if self.sprite_counter > 3:
Ver comentários do Snake.py

2021-04-08 21:02 UTC, Atsocs commented on resources/sprites/Character.json
> +    "down_3.png":
mais elegante se tirar a extensao .png desses nomes

2021-04-09 20:59 UTC, gbrlbrbs commented on components/Snake.py
> +        sprite = self.spritesheet.parse_sprite(filename)
foi passado pra spritesheet, funciona como o set_colorkey

2021-04-09 21:06 UTC, gbrlbrbs commented
agora o json é gerado automaticamente pelo [piskel](https://www.piskelapp.com/), mas os nomes gerados são do tipo "{nome da spritesheet}{numero}.png". eu mudei manualmente os nomes pra mapear do jeito que tava antes

2021-04-10 04:32 UTC, Atsocs approved these changes
Loved the bald freshman! :smiling_face_with_three_hearts:

2021-04-10 04:36 UTC, Atsocs commented
> agora o json é gerado automaticamente pelo [piskel](https://www.piskelapp.com/), mas os nomes gerados são do tipo "{nome da spritesheet}{numero}.png". eu mudei manualmente os nomes pra mapear do jeito que tava antes

favor explicar na #Reunião6 as diferenças em relação ao Tiled

2021-04-10 04:41 UTC, Atsocs reviewed
too long commit message, please consider using the [long commit form](https://stackoverflow.com/questions/9562304/git-github-commit-with-extended-message-description), also available in [`git-cola`](https://git-cola.github.io/)

2021-04-10 04:42 UTC, merged

2021-04-10 04:43 UTC, Atsocs commented
next step: powerup sprites